package nbu.team11.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import nbu.team11.entities.*;
import org.springframework.stereotype.Repository;

//Note: findByUsername is autogenerated by JPA - depending on method name and signature
@Repository
public interface UserRepository extends JpaRepository<User, Long> {
    User findByUsername(String username);
}
